version: "3.8"

services:
  backend:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5010:5010"

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - frontend
      - backend

networks:
  backend:
  frontend: